### ISSUE TITLE
访问图片报403

### ISSUE THREAD

**Issue by xgzl87** [litong19930321/dianping-react#2]
bundle.js:42622 GET http://images2015.cnblogs.com/blog/138012/201610/138012-20161022224222123-643915682.png 403 (Forbidden)

**Comment by litong19930321** [comment]
这个是直接访问项目提供的网址的，至于服务器403forbidden，我也不太知道为什么

**Comment by yuohuo** [comment]
可能是因为cnblog对图片盗链的拦截，可以图片换成本地

**Comment by mafeifan** [comment]
在public/index.html里加 `<meta name="referrer" content="no-referrer" />` 试试

**Comment by ittqqzz** [comment]
4楼说的，亲测是对的！感谢。

**Comment by mafeifan** [comment]
我这里重构了个优化版的，欢迎star。https://github.com/mafeifan/react-dianping

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by ltimon** [comment]
大概是因为对方的服务器避免非法盗用，拒绝了我们的请求，可以参考@mafeifan的解决方案，我这里加了 <meta http-equiv="Cotent-Security-Policy" content="block-all-mixed-content"/>有兴趣的可以点击这个看看https://blog.lyz810.com/article/2016/08/referrer-policy-and-anti-leech/
