### ISSUE TITLE
哥们，我你的项目运行，首页加载不出图片，可否指导一下？

### ISSUE THREAD

**Issue by Maxwell07** [litong19930321/dianping-react#3]

**Comment by ltimon** [comment]
在public/index.html里加 <meta name="referrer" content="no-referrer" /> 试试

**Comment by ltimon** [comment]
在public/index.html里加 <meta name="referrer" content="no-referrer" /> 试试

**Comment by ltimon** [comment]
<meta name="referrer" content="no-referrer" />

**Comment by ltimon** [comment]
应该是referrer的问题你在public/index.html里加 meta name="referrer" content="no-referrer"  试试
